// List of services offered at Salon David J.
// Each entry includes: id, name, category, description, duration (in minutes), and price.

const servicesData = [
  {
    id: 1,
    name: "Women's Haircut",
    category: "Cuts",
    description: "Expert haircut tailored to your style.",
    duration: 60,
    price: 70,
  },
  {
    id: 2,
    name: "Men's Haircut",
    category: "Cuts",
    description: "Classic or modern cut for men.",
    duration: 45,
    price: 45,
  },
  {
    id: 3,
    name: "Single Process Color",
    category: "Color",
    description: "Full color service for vibrant results.",
    duration: 90,
    price: 100,
  },
  {
    id: 4,
    name: "Balayage",
    category: "Color",
    description: "Natural-looking highlights technique.",
    duration: 120,
    price: 150,
  },
  {
    id: 5,
    name: "Blowout",
    category: "Styling",
    description: "Professional blowout for sleek, polished hair.",
    duration: 45,
    price: 40,
  },
  {
    id: 6,
    name: "Keratin Treatment",
    category: "Treatments",
    description: "Smooth hair and reduce frizz with long-lasting results.",
    duration: 120,
    price: 200,
  },
  {
    id: 7,
    name: "Hair Extensions",
    category: "Extensions",
    description: "Add length and volume with premium extensions.",
    duration: 180,
    price: 250,
  },
  {
    id: 8,
    name: "Deep Conditioning",
    category: "Treatments",
    description: "Revitalize and nourish hair for improved softness and shine.",
    duration: 30,
    price: 35,
  },
  {
    id: 9,
    name: "Updo Styling",
    category: "Styling",
    description: "Formal updo styling for special occasions.",
    duration: 60,
    price: 80,
  },
  {
    id: 10,
    name: "Highlights",
    category: "Color",
    description: "Partial or full highlights to brighten your look.",
    duration: 90,
    price: 120,
  },
  {
    id: 11,
    name: "Root Touch-Up",
    category: "Color",
    description: "Maintain your color by touching up your roots.",
    duration: 60,
    price: 70,
  },
  {
    id: 12,
    name: "Scalp Treatment",
    category: "Treatments",
    description: "Cleanse and invigorate your scalp for healthy hair growth.",
    duration: 30,
    price: 45,
  },
];
